### ISSUE TITLE
Cloned Groups group_title - catering for select lists

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#1113]
Hi guys,

Just playing with the new collapsible groups functionality and the ability to define 'group_title'.  Looking great so far but was wondering if there could be a minor change to the JS that creates and updated the 'group_title'.

The example I am working with has a Select list as the field that defines the 'group_title'.  The code as it is returns the 'value' of the selected option.  It would be great if it instead returned the 'text' of the option as this is far more likely to be user-facing content than the 'value' itself.

in your group.js file you have the following code on lines 61-63

```js
$field = $group.find( ':input[name*="[' + fieldId + ']"]' );

content = $field.val();
```

I am proposing changing it to the following to return, if the field is a select list, the selected option's text instead of value:

```js
$field = $group.find( ':input[name*="[' + fieldId + ']"]' );

if($field.is("select")) {
	content = $field.find('option:selected').text();
} else {
	content = $field.val();
}
```
Would love to know your thoughts on this.

Cheers,

Will

**Comment by wgstjf** [comment]
Sorry to add multiple things to one post but another thing that would be great would be to remove the 'collapsed' status from just cloned groups as inevitably they need working on straight away and also have no 'group_title' so all that displays is an empty grey bar with the 'delete' and 'order' icons :-)

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I think these 2 improvements are nice to add. So I just did it. Please update and enjoy :)

**Comment by wgstjf** [comment]
That's amazing!  Thanks for the fast response.

Might be pushing my luck here but any chance of some form of onChange for the group title?  As I see it it only gets populated once you have entered/chosen something in the specified field and saved/reloaded the page. :-)

**Comment by wgstjf** [comment]
Or maybe there is one but the following JS error is being generated when I clone a sortable/collapsible group.  Do you get the same?

```
Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'
```

Which seems to be generated from line 101 of group.js

```js
// Drag and drop clones via group title.
$( this ).sortable( 'option', 'handle', '.rwmb-clone-icon + .rwmb-group-title' );
```

**Comment by rilwis** [comment]
That error is fixed in the latest version :)

**Comment by wgstjf** [comment]
Latest version of Group?  I have 1.2.2 installed and still getting the error.  Have you updated 1.2.2 just now?

Cheers,

Will

**Comment by rilwis** [comment]
Yes, I'm using 1.2.2. Probably browser cache? Can you try clearing it?

**Comment by wgstjf** [comment]
You're right, having re-downloaded the plugin I can now see the line that performs a check first, thanks.

Is updateTitle called on a change of the group_title field or is it left to populate on a reload of the page?

Thanks as always for crazy good support :-)

**Comment by rilwis** [comment]
I use `keyup` event to check if the field is updated to provide "live update". No need to reload the page.

**Comment by wgstjf** [comment]
That explains it...I have a select list providing the group title :-)

**Comment by rilwis** [comment]
Probably I have to update again to use `change` event :)

**Comment by wgstjf** [comment]
Just changed line 70 of group.js to the following and all working as expected:

```js
$field.on( 'keyup change', _.debounce( function () {
```

**Comment by rilwis** [comment]
Yeah, that's right!

**Comment by rilwis** [comment]
Done!

**Comment by wgstjf** [comment]
Great man, thanks!
