### ISSUE TITLE
Fatal error when try to enable plugin Class 'RWMB_Core'

### ISSUE THREAD

**Issue by koda0601** [rilwis/meta-box#781]
Hi,
WordPress: 4.4.2
MetaBox: 4.8.1
PHP: 5.6

During enable I got an error:
Fatal error: Class 'RWMB_Core' not found in /wp-content/plugins/meta-box/inc/loader.php on line 125

Please help

**Comment by rilwis** [comment]
Fixed in 5c3e70608318c0a13bbb385c5cefa4c8f0556c8b

**Comment by koda0601** [comment]
still the same error. This could be wrong plugin implementation within template? I use Native Church

**Comment by rilwis** [comment]
Please send me the FTP and admin info so I can check for you https://metabox.io/contact/

**Comment by rilwis** [comment]
We just resolved the problem. The theme includes the old version of the plugin and include it to the theme directly (not via TGM Activation Class).

**Comment by CridKore** [comment]
I have this same issue.How can I solve this on my localhost?

**Comment by isar3** [comment]
Having the same problem - can anybody help me: 
 Fatal error: Class 'RWMB_Field' not found in /kunden/413373_80807/webspace/wordpress/wp-content/themes/flexform/includes/meta-box/inc/fields/altbgpreview.php on line 5

**Comment by rilwis** [comment]
@isar3 please ask the theme author of Flexform theme to update the plugin in the theme!

**Comment by isar3** [comment]
Thanx for the quick response... is there a way to just replace the plugin by an old (=working) version...? Just in case Flexform can´t update the plugin quickly.

Or is there a known workaround...? 

I don´t have any access to the site anymore and really need to be able to login again.

Many thanx and best regards,

Daniel

**Comment by rilwis** [comment]
Hi Daniel,

Yes, please try replacing this folder in the theme `wp-content/themes/flexform/includes/meta-box` with the plugin folder and see how it goes.
