### ISSUE TITLE
Can't retrieve cloned Image Advanced selected value

### ISSUE THREAD

**Issue by tanng** [rilwis/meta-box#860]
I have a clonable Image Advanced field (radio)

Now, I'll loop through each item and check if it's checked or not. I'm using this snippet:
```js
$('.rwmb-image-select input').each(function() {
	console.log($(this).is(':checked'));
});
```
If I clicked on an item, then it's checked and all others aren't. Even though they're item on other radio group.

This should be same as radio, if I click on an item, all others in current group is unchecked instead of all other radio is unchecked.

**Comment by funkedgeek** [comment]
What's the code for the field?

**Comment by tanng** [comment]
For example

```php
<?php
$meta_boxes[] = array(
		'id'         => 'layout-content',
		'title'      => 'Contenido',
		'fields'     => array(
			array(
				'name'   => 'Select Layout',
				'id'     => 'item-row',
				'type'   => 'group',
				'clone'  => true,
				'fields' => array(
					array(
						'name'     => 'Layout',
						'id'       => 'layout',
						'required' => true,
						'type'     => 'image_select',
						'options'  => array(
							'textimage' => get_bloginfo('template_url').'/images/settings/layout-textimage.png',
							'imagetext' => get_bloginfo('template_url').'/images/settings/layout-imagetext.png',
							'onlytext'  => get_bloginfo('template_url').'/images/settings/layout-text.png',
							'onlyimage' => get_bloginfo('template_url').'/images/settings/layout-image.png',
						),
					),
					array(
						'name'    => 'Text',
						'id'      => 'item-text',
						'type'    => 'textarea',
						'cols'    => 1,
						'rows'    => 5,
						'visible' => array( 'layout', 'in', array( 'onlytext', 'textimage', 'imagetext' ) ),
					),
					array(
						'name'      => 'Images',
						'id'        => 'item-images',
						'type'      => 'file_advanced',
						'mime_type' => 'image',
						'visible' => array( 'layout', 'in', array( 'onlyimage', 'textimage', 'imagetext' ) ),
					),
				),
			),
		),
	);

```

**Comment by rilwis** [comment]
@tanng I've just pushed a fix for this. The "selected" attribute is set correctly now (as it's saved correctly). Please check.

**Comment by tanng** [comment]
Sorry, but still doesn't works

I've made a screen cast for more detail
http://recordit.co/xnrNf4sUbG

**Comment by rilwis** [comment]
Hmm, here is my test http://recordit.co/WHSs33krqa, it looks fine. Can you please test with the latest version of both Meta Box (on Github) and Group extension?

**Comment by tanng** [comment]
Ok, it works with the latest Group version.
